empty list equals ['/0'] inside memory

In [ ]:
fruits = ["apple", "orange", "cherry", "grape"]

In [ ]:
f = fruits.copy()
f.append(4)
print(fruits)
print(f)

In [ ]:
e = fruits

In [ ]:
fruits.append(56)
print(fruits)
print(e)

.clear(): non-return function that clears the list<br>
.pop(): removes element by index and returns the removed element<br>
fruits.pop(1)<br>
'orange'


#Tuples

a = 1, 2, 3, 4, 5 (we can write like this)

c = 1 (just a number)

c = 1, (tuple)

a[3] = 25 (error: tuples are immutable)

#Where we use list inside list?

In game development:

2 Dimensional - 2D

In [ ]:
ls = [
    [1, 2, 36, 4],
    [2, 3, 4, 5]
]

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))

In [ ]:
a = [0,0,0,0,0,0]

In [ ]:
a = [0 for i in range(100)]

In [ ]:
a = np.zeros(100)
len(a)

In [ ]:
arr1 = np.ones((2, 3))
print(arr1)

In [ ]:
d2_list = [[], []]
for i in d2_list:
    for j in range(3):
        i.append(j)    

In [ ]:
arr3 = np.arange(0, 10)
arr3

ndim -> property that tells the number of dimensions
arr.ndim

In [ ]:
print(arr1.ndim)

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6, 7,8], [11, 22, 33, 44, 55, 66, 77, 88]])
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.astype(float))
print(np.concatenate([arr, np.array([[9, 10, 11, 12, 13, 14, 15, 16], [99, 100, 110, 120, 130, 140, 150, 160]])]))

16
2
int64
[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [11. 22. 33. 44. 55. 66. 77. 88.]]
[[  1   2   3   4   5   6   7   8]
 [ 11  22  33  44  55  66  77  88]
 [  9  10  11  12  13  14  15  16]
 [ 99 100 110 120 130 140 150 160]]
